sa_snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      threads: 16
      account: "{{ env_var('ACCOUNT', '') }}"
      user: "{{ env_var('USER', '') }}"
      database: "{{ env_var('DATABASE', '') }}"
      warehouse: "{{ env_var('WAREHOUSE', '') }}"
      schema: trouze
      role: transformer
      private_key_path: "{{ env_var('KEY_PATH', '') }}"
      private_key_passphrase: "{{ env_var('PASSPHRASE', '') }}"
    ci:
      type: snowflake
      threads: 16
      account: "{{ env_var('ACCOUNT', '') }}"
      user: "{{ env_var('USER', '') }}"
      database: "{{ env_var('DATABASE') }}"
      warehouse: "{{ env_var('WAREHOUSE', '') }}"
      schema: dbt_cloud_pr_1234_1
      role: transformer
      private_key_path: "{{ env_var('KEY_PATH', '') }}"
      private_key_passphrase: "{{ env_var('PASSPHRASE', '') }}"